_wandb:
    value:
        cli_version: 0.25.0
        e:
            ik2s45u2qpersge46k09kzv64g86brmb:
                args:
                    - seed=4
                    - model=RNN
                    - dataset=psMNIST
                    - use_wandb=true
                    - group_name=RNN
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 48
                cpu_count_logical: 48
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "405099401216"
                        used: "6921142272"
                email: singfor7012@gmail.com
                executable: /home1/aiphw227/miniconda3/envs/rnn/bin/python
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-362bcbbf-8c44-fa45-0426-9f7e9aadfb2e
                host: n009.hpc
                memory:
                    total: "810198802432"
                os: Linux-4.18.0-553.5.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /gpfs/home1/aiphw227/Delay_RNN/code/main.py
                python: CPython 3.11.14
                root: /gpfs/home1/aiphw227/Delay_RNN/code
                slurm:
                    cluster_name: cluster
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x0003FF3FF000
                    cpu_bind_list: "0x0003FF3FF000"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "20"
                    cpus_per_task: "20"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: uos
                    job_cpus_per_node: "20"
                    job_end_time: "1772106398"
                    job_gid: "100"
                    job_group: users
                    job_id: "545296"
                    job_name: bash
                    job_nodelist: n009
                    job_num_nodes: "1"
                    job_partition: gpu1
                    job_qos: node10_cpu640
                    job_start_time: "1771933598"
                    job_uid: "1291"
                    job_user: aiphw227
                    jobid: "545296"
                    launch_node_ipaddr: 192.168.140.5
                    localid: "0"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: n009
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "34975"
                    pty_win_col: "301"
                    pty_win_row: "29"
                    srun_comm_host: 192.168.140.5
                    srun_comm_port: "38383"
                    step_gpus: "2"
                    step_id: "0"
                    step_launcher_port: "38383"
                    step_nodelist: n009
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /gpfs/home1/aiphw227
                    submit_host: gate2.hpc
                    task_pid: "211216"
                    tasks_per_node: "1"
                    topology_addr: n009
                    topology_addr_pattern: node
                    tres_per_task: cpu:20
                    umask: "0022"
                startedAt: "2026-02-25T15:24:41.981309Z"
                writerId: ik2s45u2qpersge46k09kzv64g86brmb
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 41
                - 50
                - 51
            "2":
                - 1
                - 41
                - 50
                - 51
            "3":
                - 13
                - 14
                - 16
            "4": 3.11.14
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
batch_size:
    value: 128
dataset:
    value:
        _target_: datasets.sMNIST.SequentialMNIST
        input_size: 1
        permute: true
group_name:
    value: RNN
lr:
    value: 0.001
model:
    value:
        _target_: models.RNN.RNN
model_args:
    value:
        hidden_size: 128
        num_layers: 1
num_epochs:
    value: 50
num_workers:
    value: 4
seed:
    value: 4
use_lr_scheduler:
    value: true
use_wandb:
    value: true
