_wandb:
    value:
        cli_version: 0.25.0
        e:
            ttvsdqx5ue5ovhi6xn6v00le1zfnwrgb:
                args:
                    - num_workers=0
                    - seed=1
                    - model=Transformer
                    - dataset=Qswap
                    - use_wandb=true
                    - group_name=Transformer
                    - model_args.num_layers=4
                    - model_args.hidden_size=64
                codePath: main.py
                codePathLocal: main.py
                email: singfor7012@gmail.com
                executable: /home1/aiphw227/miniconda3/envs/rnn/bin/python
                host: n004.hpc
                os: Linux-4.18.0-553.5.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /gpfs/home1/aiphw227/Delay_RNN/code/main.py
                python: CPython 3.11.14
                root: /gpfs/home1/aiphw227/Delay_RNN/code
                startedAt: "2026-02-24T18:51:24.776447Z"
                writerId: ttvsdqx5ue5ovhi6xn6v00le1zfnwrgb
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 50
                - 51
            "2":
                - 1
                - 50
                - 51
            "3":
                - 13
                - 14
                - 16
            "4": 3.11.14
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
batch_size:
    value: 8
dataset:
    value:
        _target_: datasets.Qswap.Qswap
        max_seq_len: 10
        min_seq_len: 5
        one_hot_dim: 10
group_name:
    value: Transformer
lr:
    value: 0.001
model:
    value:
        _target_: models.Transformer.Transformer
        nhead: 4
model_args:
    value:
        hidden_size: 64
        num_layers: 4
num_epochs:
    value: 50
num_workers:
    value: 0
seed:
    value: 1
use_lr_scheduler:
    value: true
use_wandb:
    value: true
