

defaults:
    - _self_
    - dataset: null
    - model: null

seed: 0
num_epochs: 50
batch_size: 512
num_workers: 4

lr: 0.001

use_lr_scheduler: True
use_wandb: False

wandb:
    entity: "CIDA"
    group_name: "Test"


model_args:
    num_layers: 1
    hidden_size: 128
    


