_wandb:
    value:
        cli_version: 0.25.0
        e:
            fi43zciyobgyofqx3il9j933fs77a98l:
                args:
                    - seed=2
                    - model=MAMBA
                    - dataset=psMNIST
                    - use_wandb=true
                    - group_name=MAMBA
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 48
                cpu_count_logical: 96
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "405100871680"
                        used: "14694834176"
                email: singfor7012@gmail.com
                executable: /home1/aiphw227/miniconda3/envs/rnn/bin/python
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-eec1013d-bcbd-e7e7-a5c9-4d9fe3f6790a
                host: n014.hpc
                memory:
                    total: "810201747456"
                os: Linux-4.18.0-553.5.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /gpfs/home1/aiphw227/Delay_RNN/code/main.py
                python: CPython 3.11.14
                root: /gpfs/home1/aiphw227/Delay_RNN/code
                slurm:
                    cluster_name: cluster
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x0000000000000000000FFFFF
                    cpu_bind_list: "0x0000000000000000000FFFFF"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "20"
                    cpus_per_task: "20"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: uos
                    job_cpus_per_node: "20"
                    job_end_time: "1772115042"
                    job_gid: "100"
                    job_group: users
                    job_id: "545311"
                    job_name: bash
                    job_nodelist: n014
                    job_num_nodes: "1"
                    job_partition: gpu1
                    job_qos: node10_cpu640
                    job_start_time: "1771942242"
                    job_uid: "1291"
                    job_user: aiphw227
                    jobid: "545311"
                    launch_node_ipaddr: 192.168.140.5
                    localid: "0"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: n014
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "45725"
                    pty_win_col: "284"
                    pty_win_row: "29"
                    srun_comm_host: 192.168.140.5
                    srun_comm_port: "35469"
                    step_gpus: "0"
                    step_id: "0"
                    step_launcher_port: "35469"
                    step_nodelist: n014
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /gpfs/home1/aiphw227
                    submit_host: gate2.hpc
                    task_pid: "1684462"
                    tasks_per_node: "1"
                    topology_addr: n014
                    topology_addr_pattern: node
                    tres_per_task: cpu:20
                    umask: "0022"
                startedAt: "2026-02-24T17:32:33.574278Z"
                writerId: fi43zciyobgyofqx3il9j933fs77a98l
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 41
                - 50
                - 51
            "2":
                - 1
                - 41
                - 50
                - 51
            "3":
                - 13
                - 14
                - 16
            "4": 3.11.14
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
batch_size:
    value: 128
dataset:
    value:
        _target_: datasets.sMNIST.SequentialMNIST
        input_size: 1
        permute: true
group_name:
    value: MAMBA
lr:
    value: 0.001
model:
    value:
        _target_: models.MAMBA.MAMBA
        d_conv: 4
        d_state: 8
        expand: 2
model_args:
    value:
        hidden_size: 128
        num_layers: 1
num_epochs:
    value: 50
num_workers:
    value: 4
seed:
    value: 2
use_lr_scheduler:
    value: true
use_wandb:
    value: true
